// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajbhpqbfcpmztjtxqxxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYmhwcWJmY3BtenRqdHhxeHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzIwODQsImV4cCI6MjA2OTYwODA4NH0.t-7Ti6dRvPDPOfcwUkZ4WaYGvCsNnGBN2AO-kwrx7VI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});